name: delete

on:
  workflow_dispatch:

jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Delete Workflow Runs
        env:
          GH_TOKEN: ${{ secrets.TANEKEMGANG }}
        run: |
          WORKFLOW="test.yml"
          
          gh api -X GET /repos/tanekemgangdubois/mrcglobal1/actions/runs --paginate \
          | jq --arg WORKFLOW "$WORKFLOW" '.workflow_runs[] | select(.name == $WORKFLOW) | .id' \
          | while read -r run_id; do
              echo "Deleting Run ID $run_id"
              gh api -X DELETE "/repos/tanekemgangdubois/mrcglobal1/actions/runs/$run_id"
            done
