name: delete

on:
  workflow_dispatch:

jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: jou
        run: |
          workflow_ids=($(gh api repos/tanekemgangdubois/mrcglobal1/actions/workflows --paginate | jq '.workflows[] | select(.["state"] | contains("disabled_manually")) | .id'))

            for workflow_id in "${workflow_ids[@]}"
            do
              echo "Listing runs for the workflow ID $workflow_id"
              run_ids=( $(gh api repos/tanekemgangdubois/mrcglobal1/actions/workflows/$workflow_id/runs --paginate | jq '.workflow_runs[].id') )
              for run_id in "${run_ids[@]}"
              do
                echo "Deleting Run ID $run_id"
                gh api repos/tanekemgangdubois/mrcglobal1/actions/runs/$run_id -X DELETE >/dev/null
              done
            done
        env:
         GH_TOKEN: ${{ secrets.TANEKEMGANG }}
