name: delete

on:
  workflow_dispatch:

jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Delete Workflow Runs
        env:
          GH_TOKEN: ${{ secrets.TANEKEMGANG }}
        run: |       
          gh api -X GET /repos/tanekemgangdubois/mrcglobal1/actions/runs --paginate \
          | jq --arg WORKFLOW "test.yaml" '.workflow_runs[] | select(.name == "test.yaml") | .id' \
          | xargs -t -I{} gh api -X DELETE /repos/tanekemgangdubois/mrcglobal1/actions/runs/{}
