name: delete

on:
  workflow_dispatch:

jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: jou
        run: |
          gh api repos/tanekemgangdubois/mrcglobal1/actions/runs \
          --paginate -q '.workflow_runs[] | select(.head_branch != "main") | "\(.id)"' | \
          xargs -n1 -I % gh api repos/tanekemgangdubois/mrcglobal1/actions/runs/% -X DELETE
        env:
         GH_TOKEN: ${{ secrets.TANEKEMGANG }}
