name: Delete Workflow Runs

on:
  workflow_dispatch:
jobs:
  delete_runs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Delete old workflow runs
        run: |
          runs=$(curl -s -X GET \
            -H "Authorization: token ${{ secrets.TANEKEMGANG }}" \
            "https://api.github.com/repos/tanekemgangdubois/mrcglobal1/actions/runs")

          # Filter the workflow runs based on your criteria (e.g., delete runs older than 30 days)
          cutoff_date=$(date -u -d '30 days ago' +'%Y-%m-%dT%H:%M:%SZ')
          runs_to_delete=$(echo "$runs" | jq --arg cutoff "$cutoff_date" '.workflow_runs | map(select(.created_at < $cutoff)) | .[].id')

          # Loop through the IDs and delete each workflow run
          for run_id in $runs_to_delete; do
            echo "Deleting workflow run ID: $run_id"
            curl -s -X DELETE \
              -H "Authorization: token ${{ secrets.TANEKEMGANG }}" \
              "https://api.github.com/repos/tanekemgangdubois/mrcglobal1/actions/runs/$run_id"
          done
